import { CASES, FIELD_META, SOURCE_LIBRARY } from './data.js';
import { parseAmount, round2, computeEffective, currentRateMatches } from './logic.js';
import { loadState, saveState, clearState, blankRecord, blankDraft } from './store.js';

const SCORE_GROUPS=[
  {id:'turnover',label:'Chiffre d’affaires et déductions',weight:25,fields:['ch200','ch205','ch220','ch221','ch225','ch230','ch235','ch280']},
  {id:'taxDue',label:'Bases imposables et impôt dû',weight:25,fields:['ch303','ch313','ch343','ch383base','ch383tax']},
  {id:'inputTax',label:'Impôt préalable et corrections',weight:15,fields:['ch400','ch405','ch410','ch415','ch420']},
  {id:'funds',label:'Autres mouvements de fonds',weight:5,fields:['ch900','ch910']}
];
const store=loadState();
const state={caseIndex:Math.min(Math.max(Number(store.caseIndex)||0,0),CASES.length-1),view:['guided','extended'].includes(store.view)?store.view:'guided',mode:['learn','practice','evaluate'].includes(store.mode)?store.mode:'learn',values:{},qualification:'',validated:false,solutionShown:false,assisted:false,submitted:false,correctionShown:false,lastScore:null};
const $=sel=>document.querySelector(sel),$$=sel=>[...document.querySelectorAll(sel)],current=()=>CASES[state.caseIndex];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>{const x=parseAmount(v);return Number.isFinite(x)?x:0};
const money=v=>new Intl.NumberFormat('fr-CH',{style:'currency',currency:'CHF',minimumFractionDigits:2,maximumFractionDigits:2}).format(round2(v||0));
const num=v=>new Intl.NumberFormat('fr-CH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(round2(v||0));

function record(id=current().id){if(!store.records[id])store.records[id]=blankRecord();return store.records[id]}
function modeDrafts(id=current().id){if(!store.drafts[id])store.drafts[id]={};return store.drafts[id]}
function getDraft(){return modeDrafts()[state.mode]||blankDraft()}
function saveDraft(){modeDrafts()[state.mode]={values:{...state.values},qualification:state.qualification,assisted:Boolean(state.assisted),submitted:Boolean(state.submitted),correctionShown:Boolean(state.correctionShown),lastScore:state.lastScore};store.caseIndex=state.caseIndex;store.view=state.view;store.mode=state.mode;saveState(store)}
function loadDraft(){const d=getDraft();state.values={...(d.values||{})};state.qualification=d.qualification??'';state.assisted=state.mode==='evaluate'?false:Boolean(d.assisted);state.submitted=state.mode==='evaluate'&&Boolean(d.submitted);state.correctionShown=state.mode==='evaluate'&&Boolean(d.correctionShown);state.lastScore=state.mode==='evaluate'&&Number.isFinite(Number(d.lastScore))?Number(d.lastScore):null;state.validated=state.submitted;state.solutionShown=false}
function deleteDraft(){const d=modeDrafts();delete d[state.mode];if(!Object.keys(d).length)delete store.drafts[current().id]}
function fieldUsed(k){return current().fields.includes(k)}
function valid(k){const x=parseAmount(state.values[k]);return x!==null&&Number.isFinite(x)}
function has(k){return parseAmount(state.values[k])!==null}
function value(k){return n(state.values[k])}
function computed(){return computeEffective(state.values)}
function expectedComputed(){return computeEffective(current().expected)}

function scoreBreakdown(items,qualificationGood){const active=SCORE_GROUPS.map(group=>{const rel=items.filter(i=>group.fields.includes(i.k));return rel.length?{...group,rel,correct:rel.filter(i=>i.good).length}:null}).filter(Boolean);const totalWeight=active.reduce((s,g)=>s+g.weight,0)||1;const groups=active.map(g=>{const allocated=g.weight/totalWeight*70;return {...g,allocated,earned:allocated*(g.correct/g.rel.length)}});return {score:Math.round((qualificationGood?30:0)+groups.reduce((s,g)=>s+g.earned,0)),qualification:qualificationGood?30:0,groups}}
function sourceLinks(c){return c.sourceKeys.map(k=>SOURCE_LIBRARY[k]).filter(Boolean).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('')}
function factAmount(f){if(f[1]===0)return'—';if(String(f[2]).includes('%')&&f[1]<100)return`${f[1]} %`;return money(f[1])}

function renderTabs(){
  $('#tabs').innerHTML=CASES.map((c,i)=>{const r=store.records[c.id]||{};const cls=r.mastered?'done':(r.evaluationAttempts||r.practiceAttempts||r.learningAttempts)?'partial':r.solutionViewed?'assisted':'';return `<button class="tab ${i===state.caseIndex?'active':''}" data-case="${i}"><span class="dot ${cls}"></span>CAS ${c.id} · ${esc(c.tab)}</button>`}).join('');
  $('#caseSelect').innerHTML=CASES.map((c,i)=>`<option value="${i}" ${i===state.caseIndex?'selected':''}>${esc(c.group)} — Cas ${c.id}: ${esc(c.tab)}</option>`).join('');
  requestAnimationFrame(()=>$('#tabs .active')?.scrollIntoView({inline:'center',block:'nearest'}));
}
function renderSidebar(){
  const c=current(),r=record(),mastered=CASES.filter(x=>(store.records[x.id]||{}).bestEvaluationScore===100).length,percent=Math.round(mastered/CASES.length*100);
  const guidance=state.mode==='learn'||(state.mode==='practice'&&(r.practiceAttempts||0)>0)||(state.mode==='evaluate'&&state.correctionShown);
  const hidden=new Set(state.mode==='learn'?[]:(c.hiddenOutsideLearn||[]));
  const facts=c.facts.map((f,i)=>hidden.has(i)?'':`<div class="fact"><div class="fact-row"><div>${esc(f[0])}${state.mode==='learn'?` <span class="tag">${esc(f[2])}</span>`:''}</div><strong>${factAmount(f)}</strong></div></div>`).join('');
  const help=guidance?`<div class="legal"><strong>Base légale indicative</strong><p>${esc(c.legal)}</p><div class="case-sources">${sourceLinks(c)}</div></div><div class="checklist"><strong>Contrôles métier</strong>${c.checks.map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div>`:`<div class="guidance-locked"><strong>Aides masquées.</strong><p>${state.mode==='evaluate'?'La base légale, les contrôles et le corrigé restent masqués jusqu’à l’ouverture volontaire du corrigé.':'Validez une première tentative pour afficher les contrôles métier.'}</p></div>`;
  $('#sidebar').innerHTML=`<div><h2>${esc(c.title)}</h2><p class="meta">${esc(c.meta)}</p><span class="pill">${esc(c.level)}</span><span class="pill neutral">${esc(c.group)}</span></div><div class="task"><strong>Votre mission</strong><p>${esc(c.task)}</p></div><div><strong class="mini-title">Données du cas</strong>${facts}</div>${help}<div class="progress">Validés en évaluation: <strong>${mastered}/${CASES.length}</strong><div class="bar"><i style="width:${percent}%"></i></div></div><div class="case-nav"><button class="btn" data-prev ${state.caseIndex===0?'disabled':''}>← Précédent</button><button class="btn" data-next ${state.caseIndex===CASES.length-1?'disabled':''}>Suivant →</button></div><div class="actions"><button class="btn primary" data-verify ${state.submitted?'disabled':''}>${state.submitted?'Évaluation remise':'Vérifier mes réponses'}</button>${state.mode!=='evaluate'?'<button class="btn" data-solution>Voir la solution</button>':state.submitted&&!state.correctionShown?'<button class="btn" data-correction>Ouvrir le corrigé</button>':''}<button class="btn" data-reset>${state.mode==='evaluate'?'Nouvelle évaluation':'Recommencer ce cas'}</button><button class="btn link danger" data-reset-all>Effacer toute la progression</button></div>`;
  $('#globalProgress').textContent=`${mastered} / ${CASES.length} cas`;window.dispatchEvent(new CustomEvent('effective-progress',{detail:{mastered,total:CASES.length}}));
}
function renderInfo(){const c=current(),r=record();if(state.mode==='learn')$('#caseInfo').innerHTML=`<strong>Apprentissage.</strong> Les rubriques, explications et contrôles métier accompagnent la résolution.<br>${c.info}`;else if(state.mode==='practice')$('#caseInfo').innerHTML=`<strong>Entraînement.</strong> Analysez les faits et choisissez vous-même les rubriques.${(r.practiceAttempts||0)>0?`<br>${c.info}`:''}`;else $('#caseInfo').innerHTML=`<strong>Évaluation du cas.</strong> Aucun indice ni corrigé avant la remise.${state.submitted?' <strong>Réponses verrouillées.</strong>':''}`}
function renderQualification(){const c=current(),selected=state.qualification===''?'':Number(state.qualification),locked=state.mode==='evaluate'&&state.submitted;let feedback='';if(state.validated&&state.qualification!==''){const good=selected===c.qualification.correct,text=state.mode==='evaluate'&&!state.correctionShown?(good?'Qualification correcte.':'Qualification incorrecte.'):c.qualification.explain;feedback=`<div class="qual-feedback ${good?'ok':'bad'}">${good?'✓':'✕'} ${esc(text)}</div>`}$('#qualification').innerHTML=`<section class="qualification"><h2>1. Qualification TVA</h2><p>Cette étape représente 30 % du score.</p><select id="qualificationSelect" ${locked?'disabled':''}><option value="">${esc(c.qualification.question)}</option>${c.qualification.options.map((o,i)=>`<option value="${i}" ${selected===i?'selected':''}>${esc(o)}</option>`).join('')}</select>${feedback}</section>`}
function statusClass(k){if(!state.validated)return'pending';if(!valid(k))return'invalid';return Math.abs(value(k)-n(current().expected[k]))<=.01?'correct':'wrong'}
function input(k){const m=FIELD_META[k],parsed=parseAmount(state.values[k]),v=parsed!==null&&Number.isFinite(parsed)?num(parsed):(state.values[k]||'');return `<input class="money ${statusClass(k)}" data-field="${k}" inputmode="decimal" value="${esc(v)}" placeholder="0.00" aria-label="Chiffre ${m.code} — ${esc(m.label)}" ${state.submitted?'disabled':''}>`}
function row(k,tax=''){const m=FIELD_META[k];if(state.view==='guided'&&!fieldUsed(k))return'';return `<div class="row"><div class="code">${m.code}</div><div class="label"><strong>${m.sign||''}${esc(m.label)}</strong><small>${esc(m.sub)}</small></div><div class="input-cell">${fieldUsed(k)?input(k):'—'}</div><div class="tax-cell">${tax}</div></div>`}
function taxOnly(k){const m=FIELD_META[k];if(state.view==='guided'&&!fieldUsed(k))return'';return `<div class="row"><div class="code">${m.code}</div><div class="label"><strong>${m.sign||''}${esc(m.label)}</strong><small>${esc(m.sub)}</small></div><div class="input-cell">—</div><div class="tax-cell">${fieldUsed(k)?input(k):'—'}</div></div>`}
function computedRow(code,label,base,tax,cls=''){return `<div class="row computed ${cls}"><div class="code">${code}</div><div class="label"><strong>${esc(label)}</strong></div><div class="input-cell">${base===null?'—':money(base)}</div><div class="tax-cell">${tax===null?'':money(tax)}</div></div>`}
function acquisitionRow(){if(state.view==='guided'&&!fieldUsed('ch383base')&&!fieldUsed('ch383tax'))return'';return `<div class="row"><div class="code">383</div><div class="label"><strong>Impôt sur les acquisitions</strong><small>Contre-prestation nette et impôt dû.</small></div><div class="input-cell">${fieldUsed('ch383base')?input('ch383base'):'—'}</div><div class="tax-cell">${fieldUsed('ch383tax')?input('ch383tax'):'—'}</div></div>`}
function renderForm(){const v=computed();$('#form').innerHTML=`<section class="card"><div class="card-head"><div><h2>Vue pédagogique du décompte — méthode effective</h2><p>Saisie nette hors TVA · formulaire inspiré du prototype AFC.</p></div><span>Hors TVA</span></div><div class="columns"><div>Ch.</div><div>Description</div><div>Montant/base</div><div>Impôt</div></div><div class="section">I. Chiffre d’affaires</div>${row('ch200')}${row('ch205')}<div class="section alt">Déductions du chiffre d’affaires</div>${row('ch220')}${row('ch221')}${row('ch225')}${row('ch230')}${row('ch235')}${row('ch280')}${computedRow('289','Total des déductions',v.ch289,null)}${computedRow('299','Total du chiffre d’affaires imposable',v.ch299,null,'total')}<div class="section alt">II. Calcul de l’impôt</div>${row('ch303',money(v.t303))}${row('ch313',money(v.t313))}${row('ch343',money(v.t343))}${computedRow('379','Total des bases imposables',v.ch379,null)}${acquisitionRow()}${computedRow('399','Total de l’impôt dû',null,v.ch399,'total')}<div class="section green">Impôt préalable</div>${taxOnly('ch400')}${taxOnly('ch405')}${taxOnly('ch410')}${taxOnly('ch415')}${taxOnly('ch420')}${computedRow('479','Total de l’impôt préalable',null,v.ch479,'total')}${computedRow('500','Montant à payer à l’AFC',null,v.ch500,'balance')}${computedRow('510','Solde en faveur de l’assujetti',null,v.ch510,'balance')}<div class="section gray">III. Autres mouvements de fonds</div>${row('ch900')}${row('ch910')}</section>`}
function consistencyTips(){const c=current(),v=computed(),tips=[];const invalid=c.fields.filter(k=>has(k)&&!valid(k));if(invalid.length)tips.push('Corrigez les formats non reconnus.');const neg=c.fields.filter(k=>valid(k)&&value(k)<0);if(neg.length)tips.push('Saisissez des montants positifs; les signes des rubriques sont appliqués automatiquement.');if(valid('ch205')&&valid('ch200')&&value('ch205')>value('ch200'))tips.push('Le ch. 205 ne peut pas dépasser le ch. 200.');if(valid('ch200')&&v.ch299<-.01)tips.push('Les déductions dépassent le ch. 200.');const rates=c.fields.filter(k=>['ch303','ch313','ch343'].includes(k));if(valid('ch200')&&rates.length&&rates.every(valid)&&Math.abs(v.ch379-v.ch299)>.01)tips.push('Dans le périmètre de ces exercices, ch. 379 doit correspondre au ch. 299.');if(valid('ch383base')!==valid('ch383tax'))tips.push('Au ch. 383, renseignez la base et l’impôt.');if(valid('ch383base')&&valid('ch383tax')&&value('ch383base')>0&&!currentRateMatches(value('ch383base'),value('ch383tax')))tips.push('Le rapport base/impôt du ch. 383 ne correspond pas aux taux actuels.');return tips}
function renderPrecheck(message=''){if(message){$('#precheck').innerHTML=`<div class="precheck warn">${message}</div>`;return}const filled=current().fields.filter(valid).length;if(state.mode==='evaluate'){ $('#precheck').innerHTML=`<div class="precheck"><strong>Évaluation du cas</strong><br>${filled}/${current().fields.length} champs complétés. Les contrôles sont masqués avant la remise.</div>`;return}const tips=consistencyTips();$('#precheck').innerHTML=tips.length?`<div class="precheck warn"><strong>Points à vérifier</strong><ul>${tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`:`<div class="precheck ok"><strong>Contrôle rapide</strong><br>${filled}/${current().fields.length} champs valides. La qualification et les justificatifs restent déterminants.</div>`}
function renderResult(score,items,qualificationGood,{solution=false,assisted=false}={}){const user=computed(),expected=expectedComputed(),sealed=state.mode==='evaluate'&&!state.correctionShown&&!solution;const title=solution?'Solution affichée — aucun score autonome enregistré':state.mode==='evaluate'?(score===100?'Évaluation réussie — cas validé':'Évaluation remise — cas non validé'):score===100?'Cas correctement résolu':score>=60?'Bonne base, à consolider':'Reprenez la qualification et les rubriques';const details=sealed?`<div class="seal"><strong>Correction masquée.</strong> Ouvrez volontairement le corrigé pour voir les montants attendus.</div>`:items.map(x=>`<div class="feedback ${x.good?'ok':'bad'}"><strong>${x.good?'✓':'✕'} ch. ${FIELD_META[x.k].code}</strong><span>Votre réponse: ${money(x.user)} · attendu: ${money(x.answer)}</span><small>${esc(current().explain[x.k]||'')}</small></div>`).join('');$('#result').innerHTML=`<section class="result"><div class="result-head"><div class="score">${solution?'SOL.':score+'%'}</div><div><h2>${esc(title)}</h2><p>${items.filter(x=>x.good).length}/${items.length} champs corrects · qualification ${qualificationGood?'maîtrisée':'à revoir'}.</p></div></div><div class="result-summary"><div><span>Votre solde</span><strong>${user.ch500?money(user.ch500)+' à payer':user.ch510?money(user.ch510)+' en votre faveur':'Solde nul'}</strong></div>${sealed?'':`<div><span>Solde attendu</span><strong>${expected.ch500?money(expected.ch500)+' à payer':expected.ch510?money(expected.ch510)+' en faveur':'Solde nul'}</strong></div>`}</div>${details}<div class="result-actions">${state.mode==='evaluate'&&state.submitted&&!state.correctionShown?'<button class="btn" data-correction>Voir le corrigé et terminer</button>':''}${state.caseIndex<CASES.length-1?'<button class="btn primary" data-next>Cas suivant →</button>':''}</div></section>`;$('#result').focus({preventScroll:true});$('#result').scrollIntoView({behavior:'smooth',block:'start'})}
function verify(){const c=current();if(state.submitted)return;if(state.qualification===''){renderPrecheck('<strong>Qualification manquante.</strong> Répondez d’abord à la question TVA.');$('#qualificationSelect')?.focus();return}const missing=c.fields.filter(k=>!has(k));if(missing.length){renderPrecheck(`<strong>Champs manquants:</strong> ${missing.map(k=>'ch. '+FIELD_META[k].code).join(', ')}.`);return}const invalid=c.fields.filter(k=>!valid(k));if(invalid.length){renderPrecheck('<strong>Format invalide.</strong> Corrigez les champs concernés.');return}const neg=c.fields.filter(k=>value(k)<0);if(neg.length){renderPrecheck('<strong>Montant négatif non admis.</strong> Utilisez une valeur positive.');return}state.validated=true;const qualificationGood=Number(state.qualification)===c.qualification.correct,items=c.fields.map(k=>({k,good:Math.abs(value(k)-n(c.expected[k]))<=.01,user:value(k),answer:n(c.expected[k])})),scoring=scoreBreakdown(items,qualificationGood),r=record();if(!state.assisted){const counter={learn:'learningAttempts',practice:'practiceAttempts',evaluate:'evaluationAttempts'}[state.mode];r[counter]=(r[counter]||0)+1;r.firstScore=r.firstScore??scoring.score;if(state.mode==='learn')r.bestLearningScore=Math.max(r.bestLearningScore||0,scoring.score);if(state.mode==='practice')r.bestPracticeScore=Math.max(r.bestPracticeScore||0,scoring.score);if(state.mode==='evaluate')r.bestEvaluationScore=Math.max(r.bestEvaluationScore||0,scoring.score);r.mastered=r.bestEvaluationScore===100}if(state.mode==='evaluate'){state.submitted=true;state.lastScore=scoring.score;state.correctionShown=false}saveDraft();renderAll(false);renderResult(scoring.score,items,qualificationGood,{assisted:state.assisted})}
function solution(){if(state.mode==='evaluate')return;const c=current();record().solutionViewed=true;state.values={...c.expected};state.qualification=String(c.qualification.correct);state.assisted=true;state.validated=true;saveDraft();renderAll(false);renderResult(100,c.fields.map(k=>({k,good:true,user:n(c.expected[k]),answer:n(c.expected[k])})),true,{solution:true,assisted:true})}
function revealCorrection(){if(state.mode!=='evaluate'||!state.submitted)return;state.correctionShown=true;record().solutionViewed=true;saveDraft();renderAll(false);const c=current();renderResult(state.lastScore,c.fields.map(k=>({k,good:Math.abs(value(k)-n(c.expected[k]))<=.01,user:value(k),answer:n(c.expected[k])})),Number(state.qualification)===c.qualification.correct)}
function resetCase(){if((Object.keys(state.values).length||state.submitted)&&!confirm('Effacer les réponses de ce mode et recommencer ?'))return;deleteDraft();state.values={};state.qualification='';state.validated=false;state.assisted=false;state.submitted=false;state.correctionShown=false;state.lastScore=null;saveState(store);renderAll(false)}
function resetAll(){if(!confirm('Effacer les scores, brouillons, évaluations et résultat final de tout le parcours ?'))return;clearState();try{localStorage.removeItem('tva_effective_final_evaluation_v1')}catch{}location.reload()}
function selectCase(i){saveDraft();state.caseIndex=Number(i);store.caseIndex=state.caseIndex;saveState(store);loadDraft();renderAll(false);window.scrollTo({top:0,behavior:'auto'})}
function setMode(mode){if(state.mode===mode)return;saveDraft();state.mode=mode;store.mode=mode;saveState(store);loadDraft();renderAll(false)}
function setView(view){state.view=view;store.view=view;saveState(store);renderAll(false)}
function renderControls(){$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===state.mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$$('[data-view]').forEach(b=>{const on=b.dataset.view===state.view;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)})}
function renderAll(load=true){if(load)loadDraft();renderTabs();renderSidebar();renderInfo();renderQualification();renderForm();renderPrecheck();renderControls();bindDynamic()}
function bindDynamic(){$$('[data-case]').forEach(b=>b.onclick=()=>selectCase(b.dataset.case));$('[data-prev]')?.addEventListener('click',()=>state.caseIndex>0&&selectCase(state.caseIndex-1));$$('[data-next]').forEach(b=>b.onclick=()=>state.caseIndex<CASES.length-1&&selectCase(state.caseIndex+1));$('[data-verify]')?.addEventListener('click',verify);$('[data-solution]')?.addEventListener('click',solution);$$('[data-correction]').forEach(b=>b.onclick=revealCorrection);$('[data-reset]')?.addEventListener('click',resetCase);$('[data-reset-all]')?.addEventListener('click',resetAll);$('#qualificationSelect')?.addEventListener('change',e=>{state.qualification=e.target.value;state.validated=false;saveDraft();renderQualification();renderPrecheck()});$$('[data-field]').forEach(inp=>{inp.addEventListener('input',e=>{state.values[e.target.dataset.field]=e.target.value;state.validated=false;saveDraft();renderPrecheck()});inp.addEventListener('blur',e=>{const k=e.target.dataset.field,x=parseAmount(e.target.value);if(Number.isFinite(x)){state.values[k]=round2(x);saveDraft();renderForm();renderPrecheck();bindDynamic()}})})}
$('#caseSelect').addEventListener('change',e=>selectCase(e.target.value));$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#openMemo').addEventListener('click',()=>$('#memoDialog').showModal());$('#closeMemo').addEventListener('click',()=>$('#memoDialog').close());renderAll(true);
